# Homework {#hw}

### Chapter 1
```{r echo = FALSE, results = 'asis', warning = FALSE, message = FALSE}
library(tidyverse)
Section<- c("1.1", "1.2", "1.3", "1.4")
Problems <- c("1", "3, 5, 9, 11", "13-14, 17, 21-27 odd", "29-33 odd, 37, 40, 43")
df <- data.frame(Section, Problems)
knitr::kable(df) 
```

### Chapter 2
```{r echo = FALSE, results = 'asis', warning = FALSE, message = FALSE}
library(tidyverse)
Section<- c("2.1", "2.2", "2.3")
Problems <- c("1, 5-11 odd, 13-14, 17", "21, 23", "25-33 odd")
Notes <- c("Do the calculations for #9", "", "")
df <- data.frame(Section, Problems, Notes)
knitr::kable(df) 
```

### Chapter 3
```{r echo = FALSE, results = 'asis', warning = FALSE, message = FALSE}
library(tidyverse)
Section<- c("3.1", "3.2", "3.3", "3.4")
Problems <- c("1-11 odd", "15, 17, 21-22", "29-31, 33-35", "37-43 odd")
df <- data.frame(Section, Problems)
knitr::kable(df) 
```

### Chapter 4
```{r echo = FALSE, results = 'asis', warning = FALSE, message = FALSE}
library(tidyverse)
Section<- c("4.1", "4.3")
Problems <- c("1-9 odd", "17, 19, 23, 25")
df <- data.frame(Section, Problems)
knitr::kable(df) 
```

### Chapter 6
```{r echo = FALSE, results = 'asis', warning = FALSE, message = FALSE}
library(tidyverse)
Section<- c("6.1", "6.2", "6.3", "6.4")
Problems <- c("2-7 odd, 11, 15", "17, 22, 24, 27, 29", "31-34", "35, 39-43 odd, 46, 50")
df <- data.frame(Section, Problems)
knitr::kable(df) 
```

### Chapter 7
```{r echo = FALSE, results = 'asis', warning = FALSE, message = FALSE}
library(tidyverse)
Section<- c("7.1", "7.2", "7.3", "7.5")
Problems <- c("1-7 odd, 10, 13", "16-19, 21", "23-31 odd", "37-39, 41-45 odd")
df <- data.frame(Section, Problems)
knitr::kable(df) 
```

### Chapter 8
```{r echo = FALSE, results = 'asis', warning = FALSE, message = FALSE}
library(tidyverse)
Section<- c("8.1", "8.2", "8.3", "8.4")
Problems <- c("1-5 odd, 7-8, 11, 13-16", "19-20, 23, 25", "27-19", "32-33, 36, 39-43 odd")
df <- data.frame(Section, Problems)
knitr::kable(df) 
```
